# Generated by Django 5.1.15 on 2026-09-01 03:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical (Service Down)'), ('WARNING', 'Warning (Degraded / High Threshold)'), ('INFO', 'Informational')], db_index=True, default='CRITICAL', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], db_index=True, default='OPEN', max_length=16)),
                ('triggered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='devices.device')),
            ],
            options={
                'db_table': 'netwatch_alerts',
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['status', 'severity', 'triggered_at'], name='idx_alert_stat_sev_time'), models.Index(fields=['device', 'status'], name='idx_alert_device_stat')],
            },
        ),
    ]
