# Generated by Django 5.1.15 on 2026-09-01 06:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('devices', '0002_device_consecutive_successes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical (Service Down)'), ('WARNING', 'Warning (Degraded / High Threshold)'), ('INFO', 'Informational')], db_index=True, default='CRITICAL', max_length=16)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=16)),
                ('occurrence_count', models.PositiveIntegerField(default=1, help_text='Number of deduplicated failure occurrences during this active outage window')),
                ('first_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('timeline', models.JSONField(blank=True, default=list, help_text='Chronological event log of transitions, acknowledgments, and probe attempts')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_incidents', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='devices.device')),
            ],
            options={
                'db_table': 'netwatch_incidents',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['device', 'status'], name='idx_inc_dev_status'), models.Index(fields=['status', 'severity', 'last_seen_at'], name='idx_inc_stat_sev_time')],
            },
        ),
    ]
