# Generated by Django 5.1.15 on 2026-09-01 03:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_type', models.CharField(choices=[('ICMP_PING', 'ICMP Ping / Reachability'), ('TCP_PORT', 'TCP Port Check'), ('SNMP_POLL', 'SNMP Telemetry Poll'), ('SSH_HEALTH', 'SSH Health Check')], default='ICMP_PING', max_length=32)),
                ('port', models.PositiveIntegerField(blank=True, help_text='Target port for TCP/SSH/SNMP checks', null=True)),
                ('interval_seconds', models.PositiveIntegerField(default=30)),
                ('timeout_seconds', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('last_status', models.CharField(choices=[('SUCCESS', 'Check Succeeded'), ('FAILED', 'Check Failed'), ('TIMEOUT', 'Check Timed Out'), ('UNKNOWN', 'Not Yet Checked')], default='UNKNOWN', max_length=16)),
                ('last_latency_ms', models.FloatField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_checks', to='devices.device')),
            ],
            options={
                'db_table': 'netwatch_monitoring_checks',
                'ordering': ['device__hostname', 'check_type'],
                'unique_together': {('device', 'check_type', 'port')},
            },
        ),
        migrations.CreateModel(
            name='MonitoringLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SUCCESS', 'Check Succeeded'), ('FAILED', 'Check Failed'), ('TIMEOUT', 'Check Timed Out'), ('UNKNOWN', 'Not Yet Checked')], max_length=16)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('packet_loss', models.FloatField(default=0.0)),
                ('message', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_logs', to='devices.device')),
                ('monitoring_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='monitoring.monitoringcheck')),
            ],
            options={
                'db_table': 'netwatch_monitoring_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'timestamp'], name='idx_monlog_dev_time')],
            },
        ),
    ]
