# Generated by Django 5.1.15 on 2026-09-01 03:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(db_index=True, max_length=128, unique=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True, unpack_ipv4=True)),
                ('device_type', models.CharField(choices=[('ROUTER', 'Core / Edge Router'), ('SWITCH', 'Layer 2 / Layer 3 Switch'), ('FIREWALL', 'Next-Gen Firewall'), ('SERVER', 'Linux / Windows Server'), ('ACCESS_POINT', 'Wireless Access Point')], db_index=True, default='ROUTER', max_length=32)),
                ('vendor', models.CharField(choices=[('CISCO', 'Cisco Systems'), ('JUNIPER', 'Juniper Networks'), ('ARISTA', 'Arista Networks'), ('LINUX', 'Generic Linux'), ('GENERIC', 'Generic SNMP Device')], default='CISCO', max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=64)),
                ('os_version', models.CharField(blank=True, default='', max_length=64)),
                ('location', models.CharField(blank=True, default='Datacenter 1', max_length=128)),
                ('ssh_port', models.PositiveIntegerField(default=22)),
                ('snmp_version', models.CharField(choices=[('v2c', 'SNMP v2c'), ('v3', 'SNMP v3 (USM)')], default='v2c', max_length=8)),
                ('snmp_port', models.PositiveIntegerField(default=161)),
                ('monitoring_interval', models.PositiveIntegerField(default=30, help_text='Polling interval in seconds')),
                ('status', models.CharField(choices=[('ONLINE', 'Online / Reachable'), ('OFFLINE', 'Offline / Unreachable'), ('DEGRADED', 'Degraded / High Latency'), ('UNKNOWN', 'Unknown / Unchecked')], db_index=True, default='UNKNOWN', max_length=16)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_latency_ms', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Network Device',
                'verbose_name_plural': 'Network Devices',
                'db_table': 'netwatch_devices',
                'ordering': ['hostname'],
                'indexes': [models.Index(fields=['status', 'last_seen'], name='idx_device_status_lastseen'), models.Index(fields=['ip_address'], name='idx_device_ip')],
            },
        ),
        migrations.CreateModel(
            name='DeviceCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ssh_username', models.CharField(blank=True, default='admin', max_length=64)),
                ('_encrypted_ssh_password', models.TextField(blank=True, db_column='ssh_password', default='')),
                ('_encrypted_ssh_key', models.TextField(blank=True, db_column='ssh_private_key', default='')),
                ('_encrypted_snmp_community', models.TextField(blank=True, db_column='snmp_community', default='')),
                ('snmp_v3_user', models.CharField(blank=True, default='', max_length=64)),
                ('snmp_v3_auth_proto', models.CharField(blank=True, default='SHA', max_length=16)),
                ('_encrypted_snmp_v3_auth_key', models.TextField(blank=True, db_column='snmp_v3_auth_key', default='')),
                ('snmp_v3_priv_proto', models.CharField(blank=True, default='AES128', max_length=16)),
                ('_encrypted_snmp_v3_priv_key', models.TextField(blank=True, db_column='snmp_v3_priv_key', default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='devices.device')),
            ],
            options={
                'db_table': 'netwatch_device_credentials',
            },
        ),
        migrations.CreateModel(
            name='DeviceInterface',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. GigabitEthernet0/1 or eth0', max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('mac_address', models.CharField(blank=True, default='', max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('subnet_mask', models.CharField(blank=True, default='255.255.255.0', max_length=32)),
                ('oper_status', models.CharField(default='UP', max_length=16)),
                ('admin_status', models.CharField(default='UP', max_length=16)),
                ('speed_mbps', models.BigIntegerField(default=1000)),
                ('in_octets', models.BigIntegerField(default=0)),
                ('out_octets', models.BigIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='devices.device')),
            ],
            options={
                'db_table': 'netwatch_device_interfaces',
                'ordering': ['name'],
                'unique_together': {('device', 'name')},
            },
        ),
    ]
