# Generated by Django 5.1.15 on 2026-09-01 06:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='consecutive_successes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='failure_threshold',
            field=models.PositiveIntegerField(default=3, help_text='Consecutive failures before transitioning to DOWN'),
        ),
        migrations.AddField(
            model_name='device',
            name='recovery_threshold',
            field=models.PositiveIntegerField(default=2, help_text='Consecutive successes before transitioning from RECOVERING to UP'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('UP', 'Up / Operational'), ('ONLINE', 'Online / Reachable'), ('DEGRADED', 'Degraded / High Latency'), ('DOWN', 'Down / Critical'), ('OFFLINE', 'Offline / Unreachable'), ('RECOVERING', 'Recovering / Stabilizing'), ('UNKNOWN', 'Unknown / Unchecked')], db_index=True, default='UNKNOWN', max_length=16),
        ),
        migrations.CreateModel(
            name='DeviceStateTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=16)),
                ('to_status', models.CharField(max_length=16)),
                ('trigger', models.CharField(default='ICMP_PROBE', max_length=64)),
                ('reason', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_transitions', to='devices.device')),
            ],
            options={
                'db_table': 'netwatch_device_state_transitions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'timestamp'], name='idx_dev_trans_time')],
            },
        ),
    ]
