# Generated by Django 5.1.15 on 2026-09-01 03:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('job_type', models.CharField(choices=[('CONFIG_BACKUP', 'Configuration Backup'), ('EXECUTE_COMMAND', 'Execute Whitelisted CLI Command'), ('PING_SWEEP', 'Subnet / Group Reachability Sweep'), ('INTERFACE_BOUNCE', 'Interface State Restart')], default='EXECUTE_COMMAND', max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending in Queue'), ('RUNNING', 'Running Execution'), ('SUCCESS', 'Completed Successfully'), ('FAILED', 'Execution Failed')], db_index=True, default='PENDING', max_length=16)),
                ('command', models.TextField(blank=True, default='', help_text='Command string if job_type is EXECUTE_COMMAND')),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('target_devices', models.ManyToManyField(related_name='automation_jobs', to='devices.device')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'netwatch_automation_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
